### ISSUE TITLE
Cut a new tag v0.0.13 with PR #19 included

### ISSUE THREAD

**Issue by adammeghji** [singer-io/tap-appsflyer#33]
It seems that PR #19 has been merged (woohoo!) but the latest tag is `v0.0.13` which doesn't include this feature.  Can we bump the tag so this improvement is made available in the `master` branch?  Thanks!

**Comment by adammeghji** [comment]
bumping this! 🙏  any way I can help?

**Comment by adoankim** [comment]
bumping on this too 🙏 , and offering any help if req.

**Comment by BernalCarlos** [comment]
bumping on this too 🙏 , and offering any help if req.

**Comment by loeakaodas** [comment]
new tag cut with #34
